# KallistiOS 1.1.8
#
# mm/Makefile
# (c)2000-2001 Dan Potter
#   
# Makefile,v 1.1.1.1 2002/10/09 13:59:14 tekezo Exp

# Uncomment this line if you want normal operation
OBJS = malloc.o cplusplus.o

# Uncomment this if you want a debug malloc(). NOTE: This is not a magical
# holy grail debugging tool, it will probably screw up your code if you use
# much memory over time. See the source for details.
# OBJS = malloc_debug.o cplusplus.o

SUBDIRS =

include $(KOS_BASE)/Makefile.prefab

