# KallistiOS 1.1.8
#
# thread/Makefile
# (c)2001 Dan Potter
#   
# Makefile,v 1.1.1.1 2002/10/09 13:59:15 tekezo Exp

OBJS =  sem.o cond.o # msg.o
OBJS += thread.o
SUBDIRS = 

include $(KOS_BASE)/Makefile.prefab



