OBJS = nes_device_cclimber.o
OBJS += nes_device_gun.o
OBJS += nes_device_kbd.o
OBJS += nes_device_hypershot.o
OBJS += nes_device_mic.o
OBJS += nes_device_paddle.o
OBJS += nes_device_mahjong.o
SUBDIRS = 

include $(NESTER_BASE)/Makefile.prefab

