# KallistiOS 1.1.8
#
# arch/dreamcast/hardware/network/Makefile
# (c)2000-2001 Dan Potter
#   
# Makefile,v 1.1.1.1 2002/10/09 13:59:14 tekezo Exp

# Various network devices
OBJS = broadband_adapter.o lan_adapter.o

SUBDIRS =

include $(KOS_BASE)/Makefile.prefab



