# KallistiOS 1.1.8
#
# arch/dreamcast/navi/Makefile
# (c)2002 Dan Potter
#
# Makefile,v 1.1.1.1 2002/10/09 13:59:14 tekezo Exp

# IDE
OBJS += navi_ide.o

# Flash BIOS
OBJS += navi_flash.o

# SUBDIRS = fs
SUBDIRS =

include $(KOS_BASE)/Makefile.prefab



