OBJS = dc_menu_common.o 
OBJS += dc_menu_controller.o
OBJS += dc_menu_filelist.o 
OBJS += dc_menu_filelist_cdfs.o
OBJS += dc_menu_filelist_vmu.o
OBJS += dc_menu_filelist_vmuselect.o
OBJS += dc_menu_screenadjust.o 
SUBDIRS = 

include $(NESTER_BASE)/Makefile.prefab

