# KallistiOS 1.1.8
#
# arch/dreamcast/util/Makefile
# (c)2001 Dan Potter
#   
# Makefile,v 1.1.1.1 2002/10/09 13:59:14 tekezo Exp


OBJS = vmu_pkg.o screenshot.o
SUBDIRS = 

include $(KOS_BASE)/Makefile.prefab


