# KallistiOS 1.1.8
#
# kernel/fs/Makefile
# (c)2000-2001 Dan Potter
#   
# Makefile,v 1.1.1.1 2002/10/09 13:59:14 tekezo Exp

OBJS = fs.o fs_builtin.o fs_romdisk.o
SUBDIRS = 

include $(KOS_BASE)/Makefile.prefab

