# KallistiOS 1.1.8
#
# arch/dreamcast/fs/Makefile
# (c)2001 Dan Potter
#   
# Makefile,v 1.1.1.1 2002/10/09 13:59:14 tekezo Exp

# Dreamcast-specific file systems

OBJS = fs_iso9660.o fs_vmu.o fs_dcload.o dcload-syscall.o
SUBDIRS = 

include $(KOS_BASE)/Makefile.prefab



