# KallistiOS 1.1.8
#
# net/Makefile
# (c)2002 Dan Potter
#   
# Makefile,v 1.1.1.1 2002/10/09 13:59:14 tekezo Exp

OBJS =  net_core.o net_arp.o net_input.o net_icmp.o
SUBDIRS = 

include $(KOS_BASE)/Makefile.prefab



